[tool.poetry]
name = "pyxel-tutorial"
version = "0.1.0"
description = ""
authors = ["Marco Bakera <marco@bakera.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyxel = "^2.2.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
